{{- if and .Values.quayConfig.enabled .Values.configJob.enabled }}
{{- include "quay.config.validate" . -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: quay-config-credentials
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: quay-config-credentials
  data:
    {{- range .Values.quayConfig.users }}
    - secretKey: {{ .passwordProperty }}
      remoteRef:
        key: {{ $.Values.quayConfig.credentials.key }}
        property: {{ .passwordProperty }}
    {{- end }}
{{- end }}
