apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: {{ .Values.quay.name }}
  namespace: {{ .Values.quay.namespace | default "quay-enterprise" }}
  annotations:
    argocd.argoproj.io/sync-wave: "41"  # Layer 1: Deploy Quay Registry
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  components:
    - kind: clair
      managed: true
    - kind: horizontalpodautoscaler
      managed: true
    - kind: mirror
      managed: true
    - kind: monitoring
      managed: true
    - kind: postgres
      managed: true
      overrides:
        volumeSize: {{ .Values.quay.storage.postgres.size }}
    - kind: redis
      managed: true
    - kind: objectstorage
      managed: false
    - kind: route
      managed: true
    - kind: tls
      managed: true
    - kind: quay
      managed: true
    - kind: clairpostgres
      managed: true
      overrides:
        volumeSize: {{ .Values.quay.storage.clairpostgres.size }}
  # Secret written by the S3 job, not the Git-managed template.
  configBundleSecret: {{ .Values.quay.configBundleSecret.s3Name }}
